package entity;
// Generated 3.4.2016 20:44:27 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Casomeraci generated by hbm2java
 */
@Entity
@Table(name = "casomeraci", schema = "public")
public class Casomeraci implements java.io.Serializable {

	private int id;
	private String name;
	private String surname;
	private String mail;
	private String city;
	private String street;
	private String phone;

	public Casomeraci() {
	}

	public Casomeraci(int id, String name, String surname) {
		this.id = id;
		this.name = name;
		this.surname = surname;
	}

	public Casomeraci(String name, String surname, String mail, String city, String street, String phone) {
		this.name = name;
		this.surname = surname;
		this.mail = mail;
		this.city = city;
		this.street = street;
		this.phone = phone;	
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 30)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "mail", length = 30)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", length = 30)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Override
	public String toString() {
		return "Casomeraci [name=" + name + ", surname=" + surname + ", city=" + city + "]";
	}


}
