package entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Rozhodcovia generated by hbm2java
 */
@Entity
@Table(name = "rozhodcovia")  //, schema = "public"

public class Rozhodcovia implements Serializable {

	private int id;
	private String name;
	private String surname;
	private String mail;
	private String city;
	private String street;
	private String phone;
	private String licence;
	

	public Rozhodcovia() {
	}

	public Rozhodcovia(int id, String name, String surname) {
		this.id = id;
		this.name = name;
		this.surname = surname;
	}

	public Rozhodcovia(String name, String surname, String mail, String city, String street, String phone,
			String licence) {
		this.name = name;
		this.surname = surname;
		this.mail = mail;
		this.city = city;
		this.street = street;
		this.phone = phone;
		this.licence = licence;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 30)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "mail", length = 30)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", length = 30)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "licence", length = 2)
	public String getLicence() {
		return this.licence;
	}

	public void setLicence(String licence) {
		this.licence = licence;
	}

	@Override
	public String toString() {
		return "Rozhodcovia [id=" + id + ", name=" + name + ", surname=" + surname + ", city=" + city + "]";
	}

}
