package entity;
// Generated 3.4.2016 20:44:27 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stadiony generated by hbm2java
 */
@Entity
@Table(name = "stadiony", schema = "public")
public class Stadiony implements java.io.Serializable {

	private int id;
	private String name;
	private Timy timy;
	private String city;
	private String street;
	

	public Stadiony() {
	}

	public Stadiony(String name) {
		this.name = name;
	}

	public Stadiony(String name, Timy timy, String city, String street) {
		this.name = name;
		this.timy = timy;
		this.city = city;
		this.street = street;
	}
	public Stadiony(String name, String city, String street) {
		this.name = name;
		this.city = city;
		this.street = street;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name = "name", unique = true, nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "teamstadium")
	public Timy getTimy() {
		return this.timy;
	}

	public void setTimy(Timy timy) {
		this.timy = timy;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", length = 30)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Override
	public String toString() {
		return "Stadiony [name=" + name + ", timy=" + timy + ", city=" + city + ", street=" + street + "]";
	}


}
