package entity;
// Generated 3.4.2016 20:44:27 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Testy generated by hbm2java
 */
@Entity
@Table(name = "testy", schema = "public")
public class Testy implements java.io.Serializable {

	private int id;
	private Rozhodcovia rozhodcovia;
	private Date examdate;
	private String event;
	private Integer height;
	private Integer weight;
	private Integer rules;
	private Integer cooper;
	private Float sprint;
	private Float sprintback;
	private Float smallcross;
	private Float bigcross;
	private Float breaks;
	private Float slope;
	private String notes;

	public Testy() {
	}

	public Testy(Rozhodcovia rozhodcovia, Date examdate, String event) {
		
		this.rozhodcovia = rozhodcovia;
		this.examdate = examdate;
		this.event = event;
	}

	public Testy(Rozhodcovia rozhodcovia, Date examdate, String event, Integer height, Integer weight,
			Integer rules, Integer cooper, Float sprint, Float sprintback, Float smallcross, Float bigcross,
			Float breaks, Float slope, String notes) {
		this.rozhodcovia = rozhodcovia;
		this.examdate = examdate;
		this.event = event;
		this.height = height;
		this.weight = weight;
		this.rules = rules;
		this.cooper = cooper;
		this.sprint = sprint;
		this.sprintback = sprintback;
		this.smallcross = smallcross;
		this.bigcross = bigcross;
		this.breaks = breaks;
		this.slope = slope;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "referee_id", nullable = false)
	public Rozhodcovia getRozhodcovia() {
		return this.rozhodcovia;
	}

	public void setRozhodcovia(Rozhodcovia rozhodcovia) {
		this.rozhodcovia = rozhodcovia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "examdate", nullable = false, length = 13)
	public Date getExamdate() {
		return this.examdate;
	}

	public void setExamdate(Date examdate) {
		this.examdate = examdate;
	}

	@Column(name = "event", nullable = false, length = 30)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "rules")
	public Integer getRules() {
		return this.rules;
	}

	public void setRules(Integer rules) {
		this.rules = rules;
	}

	@Column(name = "cooper")
	public Integer getCooper() {
		return this.cooper;
	}

	public void setCooper(Integer cooper) {
		this.cooper = cooper;
	}

	@Column(name = "sprint", precision = 8, scale = 8)
	public Float getSprint() {
		return this.sprint;
	}

	public void setSprint(Float sprint) {
		this.sprint = sprint;
	}

	@Column(name = "sprintback", precision = 8, scale = 8)
	public Float getSprintback() {
		return this.sprintback;
	}

	public void setSprintback(Float sprintback) {
		this.sprintback = sprintback;
	}

	@Column(name = "smallcross", precision = 8, scale = 8)
	public Float getSmallcross() {
		return this.smallcross;
	}

	public void setSmallcross(Float smallcross) {
		this.smallcross = smallcross;
	}

	@Column(name = "bigcross", precision = 8, scale = 8)
	public Float getBigcross() {
		return this.bigcross;
	}

	public void setBigcross(Float bigcross) {
		this.bigcross = bigcross;
	}

	@Column(name = "breaks", precision = 8, scale = 8)
	public Float getBreaks() {
		return this.breaks;
	}

	public void setBreaks(Float breaks) {
		this.breaks = breaks;
	}

	@Column(name = "slope", precision = 8, scale = 8)
	public Float getSlope() {
		return this.slope;
	}

	public void setSlope(Float slope) {
		this.slope = slope;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Override
	public String toString() {
		return "Testy [id=" + id + ", rozhodcovia=" + rozhodcovia + ", examdate=" + examdate + ", event=" + event + "]";
	}

}
