package entity;
// Generated 3.4.2016 20:44:27 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Timy generated by hbm2java
 */
@Entity
@Table(name = "timy", schema = "public")
public class Timy implements java.io.Serializable {

	private int id;
	private String name;
	private String homecol;
	private String awaycol;

	public Timy() {
	}

	public Timy(String name) {
		this.name = name;
	}

	public Timy(String name, String homecol, String awaycol ) {
		this.name = name;		
		this.homecol = homecol;
		this.awaycol = awaycol;

	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name = "name", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Column(name = "homecol", length = 15)
	public String getHomecol() {
		return this.homecol;
	}

	public void setHomecol(String homecol) {
		this.homecol = homecol;
	}

	@Column(name = "awaycol", length = 15)
	public String getAwaycol() {
		return this.awaycol;
	}

	public void setAwaycol(String awaycol) {
		this.awaycol = awaycol;
	}

	@Override
	public String toString() {
		return "Timy [name=" + name + ", homecol=" + homecol + ", awaycol=" + awaycol + "]";
	}


}
