package entity;
// Generated 3.4.2016 20:44:27 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zapasy generated by hbm2java
 */
@Entity
@Table(name = "zapasy", schema = "public")
public class Zapasy implements java.io.Serializable {

	private int id;
	private Casomeraci casomeraci;
	private Rozhodcovia rozhodcoviaByCr1;
	private Rozhodcovia rozhodcoviaByHr2;
	private Rozhodcovia rozhodcoviaByCr2;
	private Rozhodcovia rozhodcoviaByHr1;
	private Stadiony stadiony;
	private Timy timyByAwayteam;
	private Timy timyByHometeam;
	private Date date;

	public Zapasy() {
	}

	public Zapasy(int id, Casomeraci casomeraci, Rozhodcovia rozhodcoviaByHr1, Stadiony stadiony, Timy timyByAwayteam,
			Timy timyByHometeam, Date date) {
		this.id = id;
		this.casomeraci = casomeraci;
		this.rozhodcoviaByHr1 = rozhodcoviaByHr1;
		this.stadiony = stadiony;
		this.timyByAwayteam = timyByAwayteam;
		this.timyByHometeam = timyByHometeam;
		this.date = date;
	}

	public Zapasy(Casomeraci casomeraci, Rozhodcovia rozhodcoviaByCr1, Rozhodcovia rozhodcoviaByHr2,
			Rozhodcovia rozhodcoviaByCr2, Rozhodcovia rozhodcoviaByHr1, Stadiony stadiony, Timy timyByAwayteam,
			Timy timyByHometeam, Date date) {
		
		this.casomeraci = casomeraci;
		this.rozhodcoviaByCr1 = rozhodcoviaByCr1;
		this.rozhodcoviaByHr2 = rozhodcoviaByHr2;
		this.rozhodcoviaByCr2 = rozhodcoviaByCr2;
		this.rozhodcoviaByHr1 = rozhodcoviaByHr1;
		this.stadiony = stadiony;
		this.timyByAwayteam = timyByAwayteam;
		this.timyByHometeam = timyByHometeam;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "casomerac", nullable = false)
	public Casomeraci getCasomeraci() {
		return this.casomeraci;
	}

	public void setCasomeraci(Casomeraci casomeraci) {
		this.casomeraci = casomeraci;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cr1")
	public Rozhodcovia getRozhodcoviaByCr1() {
		return this.rozhodcoviaByCr1;
	}

	public void setRozhodcoviaByCr1(Rozhodcovia rozhodcoviaByCr1) {
		this.rozhodcoviaByCr1 = rozhodcoviaByCr1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hr2")
	public Rozhodcovia getRozhodcoviaByHr2() {
		return this.rozhodcoviaByHr2;
	}

	public void setRozhodcoviaByHr2(Rozhodcovia rozhodcoviaByHr2) {
		this.rozhodcoviaByHr2 = rozhodcoviaByHr2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cr2")
	public Rozhodcovia getRozhodcoviaByCr2() {
		return this.rozhodcoviaByCr2;
	}

	public void setRozhodcoviaByCr2(Rozhodcovia rozhodcoviaByCr2) {
		this.rozhodcoviaByCr2 = rozhodcoviaByCr2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hr1", nullable = false)
	public Rozhodcovia getRozhodcoviaByHr1() {
		return this.rozhodcoviaByHr1;
	}

	public void setRozhodcoviaByHr1(Rozhodcovia rozhodcoviaByHr1) {
		this.rozhodcoviaByHr1 = rozhodcoviaByHr1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stadium", nullable = false)
	public Stadiony getStadiony() {
		return this.stadiony;
	}

	public void setStadiony(Stadiony stadiony) {
		this.stadiony = stadiony;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "awayteam", nullable = false)
	public Timy getTimyByAwayteam() {
		return this.timyByAwayteam;
	}

	public void setTimyByAwayteam(Timy timyByAwayteam) {
		this.timyByAwayteam = timyByAwayteam;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hometeam", nullable = false)
	public Timy getTimyByHometeam() {
		return this.timyByHometeam;
	}

	public void setTimyByHometeam(Timy timyByHometeam) {
		this.timyByHometeam = timyByHometeam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public String toString() {
		return "Zapasy [casomeraci=" + casomeraci + ", rozhodcoviaByCr1=" + rozhodcoviaByCr1 + ", rozhodcoviaByHr2="
				+ rozhodcoviaByHr2 + ", rozhodcoviaByCr2=" + rozhodcoviaByCr2 + ", rozhodcoviaByHr1=" + rozhodcoviaByHr1
				+ ", stadiony=" + stadiony + ", timyByAwayteam=" + timyByAwayteam + ", timyByHometeam=" + timyByHometeam
				+ ", date=" + date + "]";
	}

}
